### ISSUE TITLE
Doesn't work with chrome on video files

### ISSUE THREAD

**Issue by talha-asad** [koajs/koa-range#14]
With small video (mp4) files, chrome has no issues. However if I use a 34 mbish sort of a video file. It will sometimes play the first 2 secs, like (5%) of the file or just stay stuck in limbo and not respond to the request. The code I have is pretty simple:

```js
import fs from 'fs';
import Koa from 'koa';
import koaLogger from 'koa-logger';
import koaRange from 'koa-range';

const app = new Koa();
const router = new koaRouter();

app
  .use(koaLogger())
  .use(koaRange)


   /*
   * TEST VIDEO STREAM
   */
  router.get('/test', async (ctx, next) => {
    ctx.type = 'video/mp4';
    ctx.body = fs.createReadStream(__dirname + '/test.mp4');
  });

app
  .use(router.routes())
  .use(router.allowedMethods())
  .listen('3000');
```

It works fine on firefox, but I think firefox doesn't even use ranges for video.

**Comment by talha-asad** [comment]
It seems to work fine, if ctx.length is set

This means your logic for len being set to '*' is not working right

**Comment by vdegenne** [comment]
I have the exact same issue, also in the console I have these error messages :

```
  Error: write ECONNRESET
      at afterWriteDispatched (internal/stream_base_commons.js:154:25)
      at writeGeneric (internal/stream_base_commons.js:145:3)
      at Socket._writeGeneric (net.js:786:11)
      at Socket._write (net.js:798:8)
      at doWrite (_stream_writable.js:397:12)
      at clearBuffer (_stream_writable.js:550:7)
      at Socket.Writable.uncork (_stream_writable.js:332:7)
      at connectionCorkNT (_http_outgoing.js:707:8)
      at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

Could it be related ?

**Comment by yorkie** [comment]
@vdegenne What you reported error seems like the connection is reset, it should be not relevant.

**Comment by vdegenne** [comment]
@yorkie Yes but this message occurs only when I use `koa-range`. Isn't that odd ?

**Comment by masx200** [comment]
https://github.com/koajs/koa-range/issues/20

It seems that these two issues are the same.  I have fixed it.

**Comment by masx200** [comment]
https://github.com/koajs/koa-range/pull/21

**Comment by colinSnake** [comment]
hello, this problem is not solved，the warning is annoyed.
Error: write ECONNABORTED
      at afterWriteDispatched (node:internal/stream_base_commons:160:15)
      at writeGeneric (node:internal/stream_base_commons:151:3)
      at Socket._writeGeneric (node:net:817:11)
      at Socket._write (node:net:829:8)
      at doWrite (node:internal/streams/writable:408:12)
      at clearBuffer (node:internal/streams/writable:569:7)
      at Socket.Writable.uncork (node:internal/streams/writable:348:7)
      at connectionCorkNT (node:_http_outgoing:797:8)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)

**Comment by colinSnake** [comment]
**Hello,  This problem is not solved，Can you tell me a solution?**
```Error: write ECONNABORTED
      at afterWriteDispatched (node:internal/stream_base_commons:160:15)
      at writeGeneric (node:internal/stream_base_commons:151:3)
      at Socket._writeGeneric (node:net:817:11)
      at Socket._write (node:net:829:8)
      at doWrite (node:internal/streams/writable:408:12)
      at clearBuffer (node:internal/streams/writable:569:7)
      at Socket.Writable.uncork (node:internal/streams/writable:348:7)
      at connectionCorkNT (node:_http_outgoing:797:8)
      at processTicksAndRejections (node:internal/process/task_queues:82:21)
```
https://github.com/koajs/koa-range/issues/14#issuecomment-624787616

**Comment by mreinstein** [comment]
hey, What version of koa-range are you using?   I merged the fixes to git, but never published a new npm version. So unless you're referencing the latest git commit, you won't see the fixes.

**Comment by colinSnake** [comment]
sorry，i forgot this question, I used the version of "^0.3.0" for koa-range，how can i get this fix.
https://github.com/koajs/koa-range/issues/14#issuecomment-1285710696

**Comment by colinSnake** [comment]
ok, I expect to the new version, thank you for your reply. @mreinstein

**Comment by mreinstein** [comment]
@colinSnake I've merged my code to the master branch, so you can test this code by doing `npm install koajs/koa-range`.

I was going to publish these changes to npm as `0.4.0-beta` but unfortunately I don't have npm rights on the koajs org, so I can't make this happen. Hopefully installing from github will be something you can test with.

If you're able to provide any feedback I'm happy to make adjustments. 

Sorry it took so long!
